import { Farmer } from '../types';

export const initialFarmers: Farmer[] = [
  { 
    id: 1, 
    businessName: 'Ubuhinzi',
    ownerName: 'Niyokwizerwa',
    ownership: 'Youth-owned',
    commencementDate: '2024-09-15',
    province: 'East', 
    district: 'Nyagatare', 
    sector: 'Nyagatare', 
    cell: 'Nyagatare',
    village: 'Nyagatare 2',
    phone: '788445220',
    tin: 'None',
    businessType: 'Individual (solo worker)',
    participantType: 'Individual',
    companyDescription: 'Nkora ubuhinzi bwimboga mbusimburanya nibishyimbo kumboga nkunze kwibanda kuri pumpkin and cabbage...',
    supportReceived: 'Training / capacity building, eCommerce onboarding, Supporting in creating digital content',
    nationality: 'Rwandan',
    nid: '',
    ownerAge: 31,
    gender: 'Male',
    educationLevel: 'Medium', // Placeholder as not in CSV snippet for #1
    disabilityStatus: 'None',
    businessSize: 'Micro',
    revenue: 'Less than 840,000 RWF', 
    annualIncome: 'Less than 840,000 RWF',
    employees: 2,
    femaleEmployees: 1,
    youthEmployees: 1,
    valueChain: 'Cultivation of fresh produce such as maize, rice, tomatoes, fruits, and other crops.',
    permanentEmployees: false,
    status: 'Active',
    crops: []
  },
  { 
    id: 2, 
    businessName: 'Ejo heza',
    ownerName: 'Nyirahabimana Mariam',
    ownership: 'Non youth-owned',
    commencementDate: '2016-01-05',
    province: 'West', 
    district: 'Rubavu', 
    sector: 'Nyundo', 
    cell: 'Terimbere',
    village: 'Ntombe',
    phone: '786310569',
    tin: 'None',
    businessType: 'Informal Enterprise (not registered)',
    participantType: 'Enterprise/Company/Business',
    companyDescription: "Ubuhinzi bw'ibishyimbo, ibigori, imboga",
    supportReceived: 'Training / capacity building, eCommerce onboarding, Supporting in creating digital content',
    nationality: 'Rwandan',
    nid: '',
    ownerAge: 53,
    gender: 'Female',
    educationLevel: 'None',
    disabilityStatus: 'None',
    businessSize: 'Micro',
    revenue: 'Micro (less than 2 million RWF)', 
    annualIncome: 'Less than 840,000 RWF',
    employees: 0,
    femaleEmployees: 0,
    youthEmployees: 0,
    valueChain: 'Cultivation of fresh produce such as maize, rice, tomatoes, fruits, and other crops.',
    permanentEmployees: false,
    status: 'Active',
    crops: []
  },
  { 
    id: 3, 
    businessName: 'GAPERU',
    ownerName: 'GAPERU Innocent',
    ownership: 'Non youth-owned',
    commencementDate: '2022-03-25',
    province: 'West', 
    district: 'Rubavu', 
    sector: 'Nyundo', 
    cell: 'Gatovu',
    village: 'Busheru',
    phone: '783192624',
    tin: 'None',
    businessType: 'Individual (solo worker)',
    participantType: 'Association',
    companyDescription: 'Cultivates sugar cane, Beans and maize',
    supportReceived: 'Training / capacity building, eCommerce onboarding, Supporting in creating digital content',
    nationality: 'Rwandan',
    nid: '',
    ownerAge: 69,
    gender: 'Male',
    educationLevel: 'None',
    disabilityStatus: 'None',
    businessSize: 'Small',
    revenue: 'Small (2.9 - 20 million RWF)', 
    annualIncome: 'Between 2,400,000 - 3,600,000 RWF',
    employees: 5,
    femaleEmployees: 0,
    youthEmployees: 1,
    valueChain: 'Cultivation of fresh produce such as maize, rice, tomatoes, fruits, and other crops.',
    permanentEmployees: false,
    status: 'Active',
    crops: []
  },
  { 
    id: 4, 
    businessName: 'Kigali mushrooms Ltd',
    ownerName: 'Naomie MWISENEZA',
    ownership: 'Youth-owned',
    commencementDate: '2024-11-05',
    province: 'Kigali', 
    district: 'Kicukiro', 
    sector: 'Gatenga', 
    cell: 'Gatenga',
    village: 'Gatenga',
    phone: '787137180',
    tin: 'None',
    businessType: 'Informal Enterprise (not registered)',
    participantType: 'Enterprise/Company/Business',
    companyDescription: 'Kigali Mushrooms Ltd is a Rwandan agribusiness company dedicated to cultivating and selling high-quality...',
    supportReceived: 'Training / capacity building, eCommerce onboarding, Supporting in creating digital content',
    nationality: 'Rwandan',
    nid: '',
    ownerAge: 25,
    gender: 'Female',
    educationLevel: 'University',
    disabilityStatus: 'None',
    businessSize: 'Micro',
    revenue: 'Micro (less than 2 million RWF)', 
    annualIncome: 'Less than 840,000 RWF',
    employees: 2,
    femaleEmployees: 1,
    youthEmployees: 2,
    valueChain: 'Cultivation of fresh produce such as maize, rice, tomatoes, fruits, and other crops.',
    permanentEmployees: false,
    status: 'Active',
    crops: []
  },
  { 
      id: 5, 
      businessName: 'COFFEE CONNECT CENTRE LTD',
      ownerName: 'KARANGWA Felice',
      ownership: 'Youth-owned',
      commencementDate: '2023-04-18',
      province: 'Kigali', 
      district: 'Kicukiro', 
      sector: 'Gikondo', 
      cell: 'Kanserege',
      village: 'Marembo 1',
      phone: '781140324',
      tin: '121395901',
      businessType: 'Formal Enterprise (registered with RDB or RCA)',
      participantType: 'Enterprise/Company/Business',
      companyDescription: 'We grow coffee, add value to it by processing and selling it...',
      supportReceived: 'eCommerce onboarding',
      nationality: 'Rwandan',
      nid: '',
      ownerAge: 30,
      gender: 'Male',
      educationLevel: 'University',
      disabilityStatus: 'None',
      businessSize: 'Small',
      revenue: 'Small (2.9 - 20 million RWF)', 
      annualIncome: 'Between 2,400,000 - 3,600,000 RWF',
      employees: 6,
      femaleEmployees: 1,
      youthEmployees: 6,
      valueChain: 'Coffee processing and value addition',
      permanentEmployees: true,
      status: 'Active',
      crops: []
  },
  { 
      id: 6, 
      businessName: 'TPC',
      ownerName: 'Mujyambere charles',
      ownership: 'Non youth-owned',
      commencementDate: '2008-09-10',
      province: 'East', 
      district: 'Nyagatare', 
      sector: 'Tabagwe', 
      cell: 'Nyagatoma',
      village: 'Agafaru',
      phone: '788810926',
      tin: '107841209',
      businessType: 'Cooperative (Registered with RDB or RCA)',
      participantType: 'Cooperative',
      companyDescription: "Ubuhinzi bw'ibigori n'ibishyimbo no kubihunika",
      supportReceived: 'eCommerce onboarding',
      nationality: 'Rwandan',
      nid: '',
      ownerAge: 45, // Estimated
      gender: 'Male',
      educationLevel: 'None',
      disabilityStatus: 'None',
      businessSize: 'Micro',
      revenue: 'Micro (less than 2 million RWF)', 
      annualIncome: 'Between 840,000 - 1,200,000 RWF',
      employees: 1,
      femaleEmployees: 0,
      youthEmployees: 0,
      valueChain: 'Maize and Beans',
      permanentEmployees: true,
      status: 'Active',
      crops: []
  }
];
